extcode/cart_products

Configuration/TSconfig/ContentElementWizard.tsconfig

error message:
PHP Warning: Undefined array key "doktype" in /var/www/html/vendor/symfony/expression-language/Node/GetAttrNode.php line 133

traverse condition in ContentElementWizard.tsconfig

---

.github/CONTRIBUTING.md
.github/FUNDING.yml
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_question.md
.github/workflows/ci.yaml
composer.json

[TASK] Add github actions

---

Configuration/TCA/tx_cartproducts_domain_model_product_product.php

[BUGFIX] Fix label for adding file reference

---

Configuration/TCA/Overrides/pages.php

Avoid error when copying page.
Fixes #111

[BUGFIX] Add default value to TCA config

---

composer.json

[TASK] Change extcode/cart dependency to tagged version

---

Classes/Controller/ProductController.php

[BUGFIX] Return value must be of type ?Product

---

Resources/Private/Language/locallang.xlf
Resources/Private/Partials/Product/Price.html

Replaces the hard-coded text with a proper
translation.

[BUG] Use label instead of hard-coded text

---

Classes/Hooks/DatamapDataHandlerHook.php

Fixes https://github.com/extcode/cart_products/issues/107

[BUGFIX] Prevent PHP Warning: Undefined array key 'list_type' in DatamapDataHandlerHook

---

Documentation/Changelog/5.0/Breaking-135-AddJsFilesWithAssetViewHelper.rst
Documentation/Changelog/5.0/Index.rst
Documentation/Changelog/Index.rst
Resources/Private/Partials/Product/CartForm.html

Use AssetViewHelper to add JS from EXT:cart when 
needed.

[TASK] Add JS files with AssetViewHelper

---

Classes/EventListener/CheckProductAvailability.php

[BUGFIX] Fix availability check for BE variants

---

Resources/Private/Language/locallang_db.xlf

Make the difference and meaning of the two fields
more obvious.

[TASK] Improved copy in BE view of categories

---

Configuration/TCA/tx_cartproducts_domain_model_product_product.php

[TASK] Assign BE-labels to categories of product

---

Classes/ViewHelpers/Form/VariantSelectViewHelper.php

This only partly fixes the bug, the other needed
steps can be found in the comment in the #81.

[BUGFIX] Pass Frontenduser groups to ViewHelper

---

Classes/Hooks/DatamapDataHandlerHook.php

[BUGFIX] Avoid undefined array key error in PHP8.1

---

Configuration/Icons.php
ext_localconf.php

Use Icons.php for registration of Icons.
Fixes #194

[TASK] Move icon registration to `Icons.php`

---

Configuration_Extbase_Persistence_Classes.php

[TASK] Remove functionless file

---

Classes/Domain/DoctrineRepository/Product/BeVariantRepository.php
Classes/Domain/DoctrineRepository/Product/ProductRepository.php
Classes/EventListener/Order/Stock/CheckStock.php
Configuration/Services.yaml
Documentation/Changelog/5.0/Feature-138-ListenToProcessOrderCheckStockEvent.rst

[TASK] Listen to ProcessOrderCheckStock event

---

Classes/Controller/ProductController.php
Documentation/Changelog/5.0/Breaking-186-ChangedKeyForImageReferences.rst
Documentation/Changelog/5.0/Breaking-200-FrontendUserRemovedFromDetailView.rst
Documentation/Changelog/5.0/Breaking-204-MigrateSwitchableControllerActions.rst
Documentation/Changelog/5.0/Feature-138-ListenToProcessOrderCheckStockEvent.rst

[TASK] Remove FE user from detail view

---

Classes/Domain/Repository/Product/ProductRepository.php

[BUGFIX] Pad array with default order direction

---

Classes/Controller/ProductController.php

[BUGFIX] Get product from page information for SingleProduct plugin

---

Classes/Updates/SwitchableControllerActionsPluginUpdater.php

[BUGFIX] Check for a flexform registration in UpgradeWizard

---

Classes/Event/RetrieveProductsFromRequestEvent.php
Classes/Event/RetrieveProductsFromRequestEventInterface.php
Classes/EventListener/Create/CheckRequest.php
Classes/EventListener/Create/CreateCartBackendVariants.php
Classes/EventListener/Create/CreateCartFrontendVariants.php
Classes/EventListener/Create/CreateCartProduct.php

[TASK] Use BeVariantInterface and ProductInterface

---

.gitlab-ci.yml

[TASK] Remove Sonarcube configuration from GitLab CI
